增加安装脚本用户检测

diff --git a/mkrelease/install b/mkrelease/install
--- a/mkrelease/install
+++ b/mkrelease/install
@@ -1,5 +1,5 @@
 #!/bin/bash
-lines=343
+lines=350
 tail -n +$lines "$0" >/tmp/sequoiadb.tar.gz
 CURRENT_TIME=$(date "+%Y-%m-%d_%H:%M:%S")
 LOG_FILE=/tmp/install_${CURRENT_TIME}
@@ -338,5 +338,12 @@ done
 
 #确认是安装还是升级
 #校验端口号，true  false值
+local cur_user=`whoami`
+if [ "$cur_user" == "root" ]
+then
+   echo "ERROR: the installation requires root permission" >&2
+   exit 1
+fi
+
 normalComponent
 exit 0
